[package]
name = "bin_loader"
version = "0.1.0"
authors = ["NewWorldVulture <49806198+NewWorldVulture@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hidapi = "1.2.6"